package com.example.healthapp.ui.water

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import dagger.hilt.android.lifecycle.HiltViewModel
import javax.inject.Inject
import com.example.healthapp.domain.model.WaterIntake
import com.example.healthapp.utils.TimeProvider
import com.example.healthapp.data.repository.WaterRepository


/**
 * WaterViewModel
 *
 * ViewModel responsible for:
 * - Managing UI state for the Water screen
 * - Interacting with HealthRepository to load and update data
 * - Surviving configuration changes (e.g. screen rotation)
 *
 * This ViewModel does NOT hold any UI reference (View, Context).
 */
@HiltViewModel
class WaterViewModel @Inject constructor(
    private val repository: WaterRepository,
    private val timeProvider: TimeProvider
) : ViewModel() {

    /**
     * Internal mutable UI state.
     * Only the ViewModel is allowed to update this state.
     */
    private val _uiState = MutableStateFlow<WaterUiState>(WaterUiState.Loading)

    /**
     * Public immutable UI state exposed to the UI layer.
     * Activities / Fragments should collect this StateFlow
     * to render the UI.
     */
    val uiState: StateFlow<WaterUiState> = _uiState

    /**
     * Initialization block.
     *
     * This block is executed only once when the ViewModel
     * is first created.
     *
     * It will NOT be called again on:
     * - Screen rotation
     * - App going to background and coming back
     *
     * Used to load initial data.
     */
    init {
        loadWaterIntake()
    }

    /**
     * Loads today's water intake data.
     *
     * Emits different UI states:
     * - Loading: while data is being loaded
     * - Empty: when no data is available
     * - Success: when data is successfully loaded
     * - Error: when an exception occurs
     *
     * viewModelScope:
     * - Coroutine scope tied to the ViewModel lifecycle
     * - Automatically cancelled when the ViewModel is cleared
     */
    fun loadWaterIntake() {
        viewModelScope.launch {
            try {
                // Notify UI that loading has started
                _uiState.value = WaterUiState.Loading

                // Fetch today's water intake from repository
                val list = repository.getTodayWaterIntake()

                // Map domain data to UI state
                _uiState.value =
                    if (list.isEmpty()) {
                        WaterUiState.Empty
                    } else {
                        WaterUiState.Success(
                            totalAmountMl = list.sumOf { it.amountMl },
                            items = list
                        )
                    }

            } catch (e: Exception) {
                // Emit error state if something goes wrong
                _uiState.value = WaterUiState.Error(
                    e.message ?: "Unknown error"
                )
            }
        }
    }


    /**
     * Adds a new water intake record.
     *
     * After inserting the data, the ViewModel reloads
     * today's water intake to keep the UI in sync.
     *
     * UI layer only needs to call this function,
     * no manual refresh is required.
     */
    fun addWater(amountMl: Int) {
        viewModelScope.launch {
            // Insert a new water intake entry
            repository.addWaterIntake(
                WaterIntake(
                    id = 0, // Auto-generated by Room
                    amountMl = amountMl,
                    timestamp = timeProvider.now()
                )
            )
            // Reload data after insertion
            loadWaterIntake()
        }
    }
}